### ISSUE TITLE
Community Users not able to download

### ISSUE THREAD

**Issue by Vijiljones** [complanboy2/WA---Download-Group-Phone-Numbers#1]
Community Users are not able to download

**Comment by complanboy2** [comment]
Thank you for reporting. Unfortunately, WhatsApp only allows Admins to view / download the community users.

I'm opening another issue to support, Admin downloading the users from community.

**Comment by complanboy2** [comment]
https://github.com/complanboy2/WA-Download-Group-Phone-Numbers/issues/2
